## 异常

[![qTH8Rf.png](https://s1.ax1x.com/2022/04/03/qTH8Rf.png)](https://imgtu.com/i/qTH8Rf)


### 异常链
```java
public class Main {

    public static void main(String[] args) {
        test3();
        
    }

    public static void test1() throws Exception {
        throw new Exception("123");
    }

    public static void test2() throws Exception{
        try {
            test1();
        } catch (Exception e) {
            throw new Exception("456");
        }
    }

    public static void test3() {
        try {
            test2();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
}
```
发现打印的结果时`456`
异常链中连续抛出异常，会有异常信息丢失的现象，导致智慧打印捕获到的最后一个异常

有两种方法可以把之前的异常保留下来
```java
Exception(String, Exception);

或者Exception.initCause(Exception);
```